language: php

dist: bionic

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - TEST_COMMAND="vendor/bin/phpunit --verbose --coverage-text"

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
    - php: 7.2
      name: Backward compatibillity check
      env: DEPENDENCIES="roave/backward-compatibility-check" TEST_COMMAND="./.github/bc-test.sh"
    - php: 7.4
      name: phpstan
      script:
        - vendor/bin/phpstan analyse --no-progress

before_install:
    - if ! [ -z "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  - travis_retry composer install

script:
  - $TEST_COMMAND
